# Generated by Django 5.1.1 on 2025-04-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codereview', '0002_signup_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=255)),
                ('code', models.TextField(max_length=15000)),
                ('error_response', models.TextField(blank=True, max_length=15000, null=True)),
                ('enhance_response', models.TextField(blank=True, max_length=15000, null=True)),
                ('optimize_response', models.TextField(blank=True, max_length=15000, null=True)),
            ],
        ),
    ]
