# Generated by Django 5.1.1 on 2025-04-12 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codereview', '0003_codereview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='codereview',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='codereview',
            name='code',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='codereview',
            name='enhance_response',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='codereview',
            name='error_response',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='codereview',
            name='optimize_response',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
