# Generated by Django 5.1.1 on 2025-04-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codereview', '0004_codereview_user_alter_codereview_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codereview',
            name='code',
            field=models.TextField(max_length=15000),
        ),
        migrations.AlterField(
            model_name='codereview',
            name='enhance_response',
            field=models.TextField(blank=True, max_length=15000, null=True),
        ),
        migrations.AlterField(
            model_name='codereview',
            name='error_response',
            field=models.TextField(blank=True, max_length=15000, null=True),
        ),
        migrations.AlterField(
            model_name='codereview',
            name='optimize_response',
            field=models.TextField(blank=True, max_length=15000, null=True),
        ),
    ]
