# Generated by Django 5.1.1 on 2025-04-15 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codereview', '0005_alter_codereview_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codereview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codereview.signup'),
        ),
    ]
